### ISSUE TITLE
HELP!SOS

### ISSUE THREAD

**Issue by weqqdf** [post-soldier/bupt-gym#11]
好像体育馆又更新了

**Comment by giggle520** [comment]
> 好像体育馆又更新了

确实更新了吧？怎么关闭了issue ，请求好像400了？

**Comment by weqqdf** [comment]
我用第二次的可执行文件，显示数组越界了

**Comment by giggle520** [comment]
> 什么情

> 什么情况？

不知道咋了，感觉没变啥，但是就是报异常

**Comment by weqqdf** [comment]
2024-12-10 21:24:00.8568194 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:1641 onnxruntime::python::CreateInferencePybindStateModule] Init provider bridge failed.
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "main.py", line 364, in run_update_timetable
  File "main.py", line 54, in update_timetable
IndexError: list index out of range

**Comment by post-soldier** [comment]
我看看

**Comment by giggle520** [comment]
> 我看看

  有眉目吗大佬，有我们可以帮忙的地方吗？比如也一起搜搜解决方法啥的

**Comment by post-soldier** [comment]
应该是在获取timetable的时候加入了反爬，重放请求就失败了
![image](https://github.com/user-attachments/assets/17d76662-6a0a-4b06-8cd2-a0dcad49243f)
不知道是不是参数的问题，后面的参数每次都是变得，我还没找到生成的地方。
![image](https://github.com/user-attachments/assets/22eb00b2-7732-4741-b9f6-b443adeda840)
初步排除浏览器指纹的问题

**Comment by giggle520** [comment]
> 应该是在获取timetable的时候加入了反爬，重放请求就失败了 ![image](https://private-user-images.githubusercontent.com/165042370/394747545-17d76662-6a0a-4b06-8cd2-a0dcad49243f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5ODQ4OTEsIm5iZiI6MTczMzk4NDU5MSwicGF0aCI6Ii8xNjUwNDIzNzAvMzk0NzQ3NTQ1LTE3ZDc2NjYyLTZhMGEtNGIwNi04Y2QyLWEwZGNhZDQ5MjQzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMlQwNjIzMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTdiYWI5N2IxOTg0YWM5MzA1Nzc4MWQ4ZDYyNTYyMWEwM2JlOGI0ODI5NmYwODQ1N2I4MzI2NWY2MGM0ZmQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tuPXdDBbSJI45fY2FL0MalcekIpAPfYCUI69fYJ_VpE) 不知道是不是参数的问题，后面的参数每次都是变得，我还没找到生成的地方。 ![image](https://private-user-images.githubusercontent.com/165042370/394748630-22eb00b2-7732-4741-b9f6-b443adeda840.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5ODQ4OTEsIm5iZiI6MTczMzk4NDU5MSwicGF0aCI6Ii8xNjUwNDIzNzAvMzk0NzQ4NjMwLTIyZWIwMGIyLTc3MzItNDc0MS1iOWY2LWI0NDNhZGVkYTg0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMlQwNjIzMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZDI4YjI5YzM3NjBlZTgyY2I4NDAyYjAwYTNhZTA1YjMzMmQ4Y2Q2MGZlMTliMzM2YWQ3OWYxZDBjMGU3ZmUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-h3V5uZpUc8S1RP918nnkqzMYIu2Sq3Z8uQqDY3ElQM) 初步排除浏览器指纹的问题

这个会不会是后台动态生成的

**Comment by kbxzl** [comment]
现在又好了

**Comment by post-soldier** [comment]
好像又好了
